version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "S#nh@1313"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - livronet

  apilivro:
    build:
      context: .
      dockerfile: APILivro/Dockerfile
    container_name: apilivro
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=localhost,1200;Database=DesafioLivro;User Id=sa;Password=S#nh@1313;TrustServerCertificate=True;
    networks:
      - livronet
    ports:
      - "5000:80"

  desafiolivrosmvc:
    build:
      context: .
      dockerfile: src/DesafioLivrosMVC/Dockerfile
    container_name: desafiolivrosmvc
    depends_on:
      - apilivro
    environment:
      - API_BASE_URL=http://apilivro
    networks:
      - livronet
    ports:
      - "5001:80"

networks:
  livronet:
    driver: bridge
