services:
  desafiolivrosmvc:
    image: ${DOCKER_REGISTRY-}desafiolivrosmvc
    container_name: desafiolivrosmvc
    build:
      context: .
      dockerfile: src/DesafioLivrosMVC/Dockerfile
    ports:
       - "5000:5000"

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "S#nh@1313"
    ports:
      - "1433:1433"
    cap_add:
      - SYS_PTRACE

  app.api:
    image: ${DOCKER_REGISTRY-}appapi
    container_name: app.api
    build:
      context: .
      dockerfile: APILivro/Dockerfile
    ports:
      - 8080:8080 
